# Generated by Django 5.1.5 on 2025-02-04 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0003_user_follows_post_comment_user_likes"),
    ]

    operations = []
