# Generated by Django 5.1.5 on 2025-02-04 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0004_auto_20250204_1332"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="body",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="body",
            field=models.TextField(null=True),
        ),
    ]
