# Generated by Django 5.1.5 on 2025-02-04 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0005_alter_comment_body_alter_post_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="body",
            field=models.TextField(default="default"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="post",
            name="body",
            field=models.TextField(default="default"),
            preserve_default=False,
        ),
    ]
