# Generated by Django 5.1.5 on 2025-02-09 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0009_rename_post_id_comment_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images"),
        ),
    ]
