# Generated by Django 5.1.5 on 2025-02-09 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0010_user_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.ImageField(
                default="images/default_image.png", null=True, upload_to="images"
            ),
        ),
    ]
