# Generated by Django 5.1.5 on 2025-02-09 11:36

import network.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0011_alter_user_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.ImageField(
                default="images/default_image.png",
                null=True,
                upload_to=network.models.User.custom_image_path,
            ),
        ),
    ]
